import type { Area, SeedCategory } from "./types";

// 미션뱅크 DB(심화·확장판)의 26개 카테고리를 구조화된 데이터로 인코딩.
// 시드는 "정답"이 아니라 LLM 변주용 씨앗이다(그대로 복붙 금지).
// 근거태그: BA=행동활성화, EXP=단계적노출, SE=자기효능감,
//          EW=표현적글쓰기, IPS=지원고용, CIRC=일주기·수면, KOR=국내실태·회복연구.

export const CATEGORIES: SeedCategory[] = [
  // ── ① 생활리듬 ─────────────────────────────────────────────
  {
    id: "1-A",
    area: "rhythm",
    name: "기상·취침 앵커",
    levels: { min: 1, max: 5 },
    evidence: ["BA", "CIRC"],
    seeds: [
      "오늘 일어난 시간 기록하기",
      "알람 하나 맞춰두기",
      "기상 후 5분 안에 앉아보기",
      "취침 전 화면 끄는 시각 정하기",
      "3일 연속 기상 시간 적어보기",
      "오늘 몇 시쯤이 제일 개운했는지 표시하기",
    ],
    variationHint: "시간대(자기 전/아침) · 형식(기록↔행동)",
    reflectQs: ["오늘 리듬은 어제와 비교해 어땠어요?"],
  },
  {
    id: "1-B",
    area: "rhythm",
    name: "빛과 공기",
    levels: { min: 1, max: 4 },
    evidence: ["CIRC", "BA"],
    seeds: [
      "커튼 열기",
      "창문 5분 열어 환기하기",
      "아침 햇빛 3분 쬐기",
      "방 불 켜기",
      "낮에 가장 밝은 곳으로 자리 옮기기",
    ],
    variationHint: "취향(식물→창가 화분에 빛 쬐어주기) · 시간대(아침 고정)",
    reflectQs: ["빛과 공기를 느끼니 어땠어요?"],
  },
  {
    id: "1-C",
    area: "rhythm",
    name: "식사 리듬",
    levels: { min: 1, max: 5 },
    evidence: ["BA", "KOR"],
    seeds: [
      "물 한 컵 마시기",
      "오늘 먹은 것 하나 기록하기",
      "정해진 시간에 간단히 한 끼 먹기",
      "배고픔 신호 한 번 알아차리기",
      "내일 먹을 것 하나 정해두기",
      "냉장고·찬장 살펴 먹을 것 파악하기",
    ],
    variationHint: "취향(요리→5분 요리 하나) · 형식(기록형: 식사 시간만 적기)",
    reflectQs: ["다음에 또 한다면 어떻게 하고 싶어요?"],
  },
  {
    id: "1-D",
    area: "rhythm",
    name: "수분·기본 신체",
    levels: { min: 1, max: 3 },
    evidence: ["BA"],
    seeds: ["물 한 컵 마시기", "30초 스트레칭하기", "창가에서 기지개 켜기", "손 씻기"],
    reflectQs: ["몸이 조금 개운해졌나요?"],
  },
  {
    id: "1-E",
    area: "rhythm",
    name: "하루 구조화",
    levels: { min: 1, max: 4 },
    evidence: ["BA", "SE"],
    seeds: [
      "오늘 할 아주 작은 일 하나 정하기",
      "하루를 세 칸으로 나눠 한 칸에 뭐 했는지 적기",
      "알람 하나로 하루의 시작 신호 만들기",
      "내일의 첫 행동 하나 정해두기",
    ],
    variationHint: "형식(기록형 중심)",
    reflectQs: ["하루를 나눠보니 어땠어요?"],
  },
  {
    id: "1-F",
    area: "rhythm",
    name: "리듬 자각·기록",
    levels: { min: 1, max: 3 },
    evidence: ["BA"],
    seeds: [
      "어제 잔 시간 표시하기",
      "오늘 컨디션 이모지 하나 고르기",
      "요즘 하루 흐름 한 줄 적기",
      "잘 되는 시간대 하나 찾아보기",
    ],
    reflectQs: ["기록해보니 어땠어요?"],
  },

  // ── ② 자기돌봄 / 신체·정서 ─────────────────────────────────
  {
    id: "2-A",
    area: "selfcare",
    name: "위생·몸단장",
    levels: { min: 1, max: 4 },
    evidence: ["BA", "KOR"],
    seeds: [
      "세수 또는 양치하기",
      "손·얼굴 물로 씻기",
      "머리 빗기",
      "옷 갈아입기",
      "샤워하기",
      "오늘 할 수 있는 몸단장 하나 고르기",
    ],
    variationHint: "형식(행동형) · 난이도(세수→샤워)",
    reflectQs: ["하고 나니 조금 달라진 게 있었어요?"],
  },
  {
    id: "2-B",
    area: "selfcare",
    name: "감정 자각·기록",
    levels: { min: 1, max: 5 },
    evidence: ["EW", "BA"],
    seeds: [
      "지금 기분 이모지 하나 고르기",
      "오늘 감정 한 단어로 적기",
      "오늘 감정 한 줄 쓰기",
      "오늘 그나마 괜찮았던 순간 하나 적기",
      "오늘 힘들었던 것 한 줄 적기",
    ],
    variationHint: "취향(음악→기분에 맞는 곡, 그림→기분을 색으로) · 형식(기록형 기본)",
    reflectQs: ["적어보니 마음이 조금 정리됐어요?"],
  },
  {
    id: "2-C",
    area: "selfcare",
    name: "몸 움직이기(실내)",
    levels: { min: 1, max: 4 },
    evidence: ["BA"],
    seeds: [
      "목·어깨 30초 스트레칭하기",
      "방 안 3분 걷기",
      "제자리에서 기지개 켜기",
      "10분 스트레칭하기",
      "좋아하는 종목 영상 보며 동작 하나 따라하기",
    ],
    variationHint: "취향(스포츠·음악에 맞춰 몸 흔들기)",
    reflectQs: ["몸을 움직이니 어땠어요?"],
  },
  {
    id: "2-D",
    area: "selfcare",
    name: "바깥과 연결(외출 노출)",
    levels: { min: 1, max: 5 },
    evidence: ["EXP", "SE"],
    gate: { forbiddenTags: ["외출"], minCondition: "그저 그럼" },
    seeds: [
      "창가에서 바깥 5분 바라보기",
      "현관문 앞까지 나가보기",
      "집 앞·복도까지 나가보기",
      "근처 편의점·우체통까지 다녀오기",
      "동네 한 바퀴 걷기",
    ],
    variationHint:
      "기록형으로 낮추기(가보고 싶은 근처 장소 하나 찾아두기) · 취향(동물→산책하는 강아지 구경, 식물→동네 나무 하나 보기)",
    reflectQs: ["밖에서 뭐가 제일 괜찮았어요?"],
  },
  {
    id: "2-E",
    area: "selfcare",
    name: "공간 돌보기",
    levels: { min: 1, max: 4 },
    evidence: ["BA", "KOR"],
    seeds: [
      "눈앞 물건 하나 제자리에 두기",
      "쓰레기 하나 버리기",
      "책상 위 한 뼘만 정리하기",
      "이불 정리하기",
      "5분 타이머로 정리하기",
    ],
    variationHint: "한 뼘만·하나만 원칙으로 부담 최소화",
    reflectQs: ["정돈된 자리를 보니 어땠어요?"],
  },
  {
    id: "2-F",
    area: "selfcare",
    name: "취향·몰입",
    levels: { min: 1, max: 4 },
    evidence: ["BA", "KOR"],
    seeds: [
      "좋아하는 음악 한 곡 듣기",
      "좋아하는 글·웹툰 한 편 보기",
      "보던 영상 중 제일 좋았던 것 한 줄 메모하기",
      "관심 있는 것 5분 찾아보기",
    ],
    variationHint: "취향별 소재 교체(동물→동물 영상, 요리→먹고 싶은 것 검색)",
    reflectQs: ["오늘 본·들은 건 어느 쪽이었어요?"],
  },
  {
    id: "2-G",
    area: "selfcare",
    name: "자기연민·인지(저강도)",
    levels: { min: 1, max: 3 },
    evidence: ["SE", "EW"],
    seeds: [
      "오늘 나에게 해주고 싶은 말 한 줄 적기",
      "오늘 잘한 아주 작은 것 하나 적기",
      "이 정도면 괜찮다 한 번 말해보기",
    ],
    variationHint: "저강도만. 추상적 조언·강요 금지",
    reflectQs: ["나에게 말해주니 어땠어요?"],
  },

  // ── ③ 관계 (대인접촉 게이트 통과 후) ───────────────────────
  {
    id: "3-A",
    area: "relationship",
    name: "비대면 관찰",
    levels: { min: 1, max: 1 },
    evidence: ["EXP", "KOR"],
    seeds: [
      "안 읽은 메시지 하나 '읽음'만 하기",
      "관심 커뮤니티 글 1개 읽어보기",
      "예전 대화 하나 스크롤해 보기",
    ],
    reflectQs: ["읽어보니 어땠어요?"],
  },
  {
    id: "3-B",
    area: "relationship",
    name: "비대면 흔적 남기기",
    levels: { min: 2, max: 2 },
    evidence: ["EXP"],
    seeds: [
      "관심 글에 이모지 하나 남기기",
      "마음에 드는 글에 좋아요 하나 누르기",
      "짧은 댓글 한 줄 남기기",
    ],
    reflectQs: ["흔적을 남겨보니 어땠어요?"],
  },
  {
    id: "3-C",
    area: "relationship",
    name: "비대면 소통(비동기)",
    levels: { min: 2, max: 4 },
    evidence: ["EXP", "SE"],
    seeds: [
      "보내지 않을 안부 메시지 초안 쓰기",
      "저장해둔 안부 메시지 초안 하나 보내보기",
      "짧은 감사 메시지 한 줄 보내기",
    ],
    variationHint: "초안(부치지 않는 편지)로 부담 없이 연습 후 발송 · 자기 속도",
    reflectQs: ["보내고 나서 어땠어요?"],
  },
  {
    id: "3-D",
    area: "relationship",
    name: "약한 유대",
    levels: { min: 3, max: 4 },
    evidence: ["EXP", "KOR"],
    gate: { forbiddenTags: ["외출", "대면"] },
    seeds: [
      "온라인 커뮤니티에 질문 하나 올리기",
      "관심사 오픈채팅 눈팅하다 한마디 남기기",
      "편의점 직원에게 눈인사 건네기",
    ],
    reflectQs: ["작게 건네보니 어땠어요?"],
  },
  {
    id: "3-E",
    area: "relationship",
    name: "신뢰 인물 1명",
    levels: { min: 4, max: 5 },
    evidence: ["EXP", "KOR"],
    gate: { forbiddenTags: ["전화", "대면"] },
    seeds: [
      "편한 가족·지인 1명에게 한 줄 안부 보내기",
      "잘 지내냐는 메시지에 답하기",
      "짧은 통화 한 번 걸어보기",
    ],
    variationHint: "신뢰 인물 존재 + 부담 낮을 때만. 가족 부담 시 가족 대상 제외",
    reflectQs: ["마음을 나눠보니 어땠어요?"],
  },
  {
    id: "3-F",
    area: "relationship",
    name: "또래·자조",
    levels: { min: 2, max: 5 },
    evidence: ["KOR", "SE"],
    seeds: [
      "비슷한 경험 커뮤니티 글 하나 읽기",
      "자조 모임·온라인 모임 정보 하나 찾아보기",
      "익명으로 한마디 남기기",
    ],
    reflectQs: ["같은 경험을 보니 어땠어요?"],
  },

  // ── ④ 사회진입 / 경제·활동 ─────────────────────────────────
  {
    id: "4-A",
    area: "social",
    name: "관심·강점 탐색",
    levels: { min: 1, max: 2 },
    evidence: ["IPS", "SE"],
    seeds: [
      "관심 직무·분야 하나 골라보기",
      "해봤던 것 중 그나마 나았던 것 하나 떠올리기",
      "내가 좋아하는 활동 3가지 적어보기",
      "오늘 관심사와 연결되는 일 상상해보기",
    ],
    variationHint: "취향 전부 활용(게임→게임 관련 직무 구경 등)",
    reflectQs: ["생각해보니 어땠어요?"],
  },
  {
    id: "4-B",
    area: "social",
    name: "정보 탐색",
    levels: { min: 2, max: 3 },
    evidence: ["IPS", "BA"],
    seeds: [
      "관심 분야 정보 5분 검색하기",
      "관심 직무 하는 사람 영상 하나 보기",
      "관심 분야 용어 하나 찾아보기",
    ],
    variationHint: "탐색형(콘텐츠 선호자에 적합)",
    reflectQs: ["새로 알게 되니 어땠어요?"],
  },
  {
    id: "4-C",
    area: "social",
    name: "자기표현·기록",
    levels: { min: 3, max: 4 },
    evidence: ["IPS", "EW", "SE"],
    seeds: [
      "내 강점 한 줄 적어보기",
      "이력서에 넣을 한 문장 써보기",
      "해본 일 하나 적어보기",
      "자기소개 한 줄 써보기",
    ],
    reflectQs: ["적어보니 어땠어요?"],
  },
  {
    id: "4-D",
    area: "social",
    name: "자원 연계",
    levels: { min: 3, max: 4 },
    evidence: ["IPS", "KOR"],
    seeds: [
      "우리 지역 청년지원 정보 하나 저장하기",
      "무료로 쓸 수 있는 공간 하나 찾아보기",
      "관심 프로그램 하나 저장하기",
    ],
    reflectQs: ["찾아보니 도움이 될 것 같아요?"],
  },
  {
    id: "4-E",
    area: "social",
    name: "경제 기초(정보)",
    levels: { min: 2, max: 4 },
    evidence: ["KOR"],
    seeds: [
      "받을 수 있는 지원금 하나 검색하기",
      "교통비·밥값 지원 정보 찾아보기",
      "관심 알바 유형 하나 알아보기",
      "무료 강의·자원 하나 저장하기",
    ],
    variationHint: "무비용 원칙. 결제·구매·유료 미션 금지, 정보 탐색만",
    reflectQs: ["알아보니 어땠어요?"],
  },
  {
    id: "4-F",
    area: "social",
    name: "소규모 경제·실전(외출 겸)",
    levels: { min: 3, max: 5 },
    evidence: ["EXP", "IPS"],
    gate: { forbiddenTags: ["외출"], minCondition: "그저 그럼" },
    seeds: [
      "편의점·카페에서 직접 주문해보기",
      "무인점포 이용해보기",
      "가까운 곳에서 필요한 것 하나 사보기",
    ],
    variationHint: "노출+경제활동 동시. 무리한 금액 금지",
    reflectQs: ["해보니 생각보다 어땠어요?"],
  },
  {
    id: "4-G",
    area: "social",
    name: "학습·역량",
    levels: { min: 2, max: 4 },
    evidence: ["IPS", "BA"],
    seeds: [
      "관심 분야 5분 학습하기",
      "무료 강의 1강 들어보기",
      "궁금한 것 하나 검색해 정리하기",
      "관심 주제 글 한 쪽 읽기",
    ],
    reflectQs: ["배워보니 어땠어요?"],
  },
];

export const CATEGORIES_BY_AREA: Record<Area, SeedCategory[]> = {
  rhythm: CATEGORIES.filter((c) => c.area === "rhythm"),
  selfcare: CATEGORIES.filter((c) => c.area === "selfcare"),
  relationship: CATEGORIES.filter((c) => c.area === "relationship"),
  social: CATEGORIES.filter((c) => c.area === "social"),
};

// 취향(관심사) → 각 영역에서 녹이는 법 (변주축 A)
export const INTEREST_HINTS: Record<string, Partial<Record<Area, string>>> = {
  게임: {
    rhythm: "잘 시각 정하기(밤샘 방지)",
    selfcare: "게임 후 가벼운 스트레칭",
    relationship: "길드·커뮤니티 글 읽기",
    social: "게임 관련 직무 구경",
  },
  음악: {
    rhythm: "기상 음악 정하기",
    selfcare: "기분에 맞는 곡 고르기",
    relationship: "플레이리스트 공유 글 보기",
    social: "음악 관련 활동 탐색",
  },
  동물: {
    selfcare: "동물 영상 보기",
    relationship: "반려동물 커뮤니티 글 보기",
    social: "관련 봉사·일 탐색",
  },
  식물: {
    rhythm: "창가 화분에 빛 쬐어주기",
    selfcare: "식물 하나 돌보기",
    relationship: "식집사 커뮤니티 글 보기",
    social: "원예 정보 탐색",
  },
  "요리·먹는 것": {
    rhythm: "5분 요리 한 끼",
    selfcare: "먹고 싶은 것 검색",
    relationship: "맛집 글 읽기",
    social: "관련 알바·일 탐색",
  },
  "책·글": {
    rhythm: "자기 전 한 쪽 읽기",
    selfcare: "좋아하는 글 한 편",
    relationship: "독서 커뮤니티 글 보기",
    social: "관심 주제 학습",
  },
  스포츠: {
    rhythm: "아침 스트레칭",
    selfcare: "동작 하나 따라하기",
    relationship: "팀·경기 커뮤니티 글 보기",
    social: "관련 활동 탐색",
  },
  "그림·만들기": {
    selfcare: "기분을 색·낙서로 표현",
    relationship: "창작 커뮤니티 글 보기",
    social: "포트폴리오 한 조각",
  },
};
